title: Sticky Frog Fingers
author: Zac Coventry
email: frog-fingers@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for tree frog enthusiasts.
theme: minima

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
